name: polisense
description: A news and politics tracking app for US politics with AI-generated summaries and headlines.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  share_plus: ^7.0.2
  url_launcher: ^6.1.12
  flutter_markdown: ^0.6.15
  google_fonts: ^5.1.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  
  # State management
  flutter_riverpod: ^2.3.6
  
  # Navigation
  go_router: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 